# Generated by Django 5.1.4 on 2024-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
    ]
